spring.application.name=auth service
server.port=8082

jwt.secret=claveSuperSeguraParaSeniorCare123!
jwt.expiration=3600000

user.service.url=http://localhost:8081/api/users
user.service.findByEmail=/by-email?email=

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
