version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: seniorcare-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}      # 👈  obligatorio
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql


  backend:
    build: .
    container_name: seniorcare-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
