version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: seniorcare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: seniorcare_db
      MYSQL_USER: senior
      MYSQL_PASSWORD: senior123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - seniorcare-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

networks:
  seniorcare-net:
    driver: bridge
