server:
  port: 8083

spring:
  application:
    name: care-request-service

  datasource:
    # Use mysql-db:3306 when running inside Docker network
    url: jdbc:mysql://localhost:3307/seniorcare_db?useSSL=false&serverTimezone=UTC
    username: senior
    password: senior123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


external:
  user-service:
    url: http://localhost:8081/api/users
    get-by-id: /{id}
  carer-service:
    url: http://localhost:8082/api/carer
    get-by-id: /{id}
  specialty-service:
    url: http://localhost:8084/api/specialty
    get-all: /all
